// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: artifact.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactType int32

const (
	ArtifactType_ARTIFACT_TYPE_UNSPECIFIED   ArtifactType = 0
	ArtifactType_ARTIFACT_TYPE_BLOB          ArtifactType = 1
	ArtifactType_ARTIFACT_TYPE_COMMIT        ArtifactType = 2
	ArtifactType_ARTIFACT_TYPE_PR            ArtifactType = 3
	ArtifactType_ARTIFACT_TYPE_IMAGE         ArtifactType = 4
	ArtifactType_ARTIFACT_TYPE_TEST_REPORT   ArtifactType = 5
	ArtifactType_ARTIFACT_TYPE_BUILD_LOG     ArtifactType = 6
	ArtifactType_ARTIFACT_TYPE_DEPLOY_RECORD ArtifactType = 7
)

// Enum value maps for ArtifactType.
var (
	ArtifactType_name = map[int32]string{
		0: "ARTIFACT_TYPE_UNSPECIFIED",
		1: "ARTIFACT_TYPE_BLOB",
		2: "ARTIFACT_TYPE_COMMIT",
		3: "ARTIFACT_TYPE_PR",
		4: "ARTIFACT_TYPE_IMAGE",
		5: "ARTIFACT_TYPE_TEST_REPORT",
		6: "ARTIFACT_TYPE_BUILD_LOG",
		7: "ARTIFACT_TYPE_DEPLOY_RECORD",
	}
	ArtifactType_value = map[string]int32{
		"ARTIFACT_TYPE_UNSPECIFIED":   0,
		"ARTIFACT_TYPE_BLOB":          1,
		"ARTIFACT_TYPE_COMMIT":        2,
		"ARTIFACT_TYPE_PR":            3,
		"ARTIFACT_TYPE_IMAGE":         4,
		"ARTIFACT_TYPE_TEST_REPORT":   5,
		"ARTIFACT_TYPE_BUILD_LOG":     6,
		"ARTIFACT_TYPE_DEPLOY_RECORD": 7,
	}
)

func (x ArtifactType) Enum() *ArtifactType {
	p := new(ArtifactType)
	*p = x
	return p
}

func (x ArtifactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactType) Descriptor() protoreflect.EnumDescriptor {
	return file_artifact_proto_enumTypes[0].Descriptor()
}

func (ArtifactType) Type() protoreflect.EnumType {
	return &file_artifact_proto_enumTypes[0]
}

func (x ArtifactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactType.Descriptor instead.
func (ArtifactType) EnumDescriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{0}
}

// Artifact is content-addressed by id (sha256 of blob_ref content).
type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // sha256
	Type          ArtifactType           `protobuf:"varint,2,opt,name=type,proto3,enum=agentlens.v1.ArtifactType" json:"type,omitempty"`
	Meta          *structpb.Struct       `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	BlobRef       string                 `protobuf:"bytes,4,opt,name=blob_ref,json=blobRef,proto3" json:"blob_ref,omitempty"` // s3://bucket/key or local path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetType() ArtifactType {
	if x != nil {
		return x.Type
	}
	return ArtifactType_ARTIFACT_TYPE_UNSPECIFIED
}

func (x *Artifact) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Artifact) GetBlobRef() string {
	if x != nil {
		return x.BlobRef
	}
	return ""
}

var File_artifact_proto protoreflect.FileDescriptor

const file_artifact_proto_rawDesc = "" +
	"\n" +
	"\x0eartifact.proto\x12\fagentlens.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x92\x01\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.agentlens.v1.ArtifactTypeR\x04type\x12+\n" +
	"\x04meta\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04meta\x12\x19\n" +
	"\bblob_ref\x18\x04 \x01(\tR\ablobRef*\xeb\x01\n" +
	"\fArtifactType\x12\x1d\n" +
	"\x19ARTIFACT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ARTIFACT_TYPE_BLOB\x10\x01\x12\x18\n" +
	"\x14ARTIFACT_TYPE_COMMIT\x10\x02\x12\x14\n" +
	"\x10ARTIFACT_TYPE_PR\x10\x03\x12\x17\n" +
	"\x13ARTIFACT_TYPE_IMAGE\x10\x04\x12\x1d\n" +
	"\x19ARTIFACT_TYPE_TEST_REPORT\x10\x05\x12\x1b\n" +
	"\x17ARTIFACT_TYPE_BUILD_LOG\x10\x06\x12\x1f\n" +
	"\x1bARTIFACT_TYPE_DEPLOY_RECORD\x10\aB/Z-github.com/dong-qiu/agent-lens/internal/pb;pbb\x06proto3"

var (
	file_artifact_proto_rawDescOnce sync.Once
	file_artifact_proto_rawDescData []byte
)

func file_artifact_proto_rawDescGZIP() []byte {
	file_artifact_proto_rawDescOnce.Do(func() {
		file_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artifact_proto_rawDesc), len(file_artifact_proto_rawDesc)))
	})
	return file_artifact_proto_rawDescData
}

var file_artifact_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_artifact_proto_goTypes = []any{
	(ArtifactType)(0),       // 0: agentlens.v1.ArtifactType
	(*Artifact)(nil),        // 1: agentlens.v1.Artifact
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_artifact_proto_depIdxs = []int32{
	0, // 0: agentlens.v1.Artifact.type:type_name -> agentlens.v1.ArtifactType
	2, // 1: agentlens.v1.Artifact.meta:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_artifact_proto_init() }
func file_artifact_proto_init() {
	if File_artifact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifact_proto_rawDesc), len(file_artifact_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_artifact_proto_goTypes,
		DependencyIndexes: file_artifact_proto_depIdxs,
		EnumInfos:         file_artifact_proto_enumTypes,
		MessageInfos:      file_artifact_proto_msgTypes,
	}.Build()
	File_artifact_proto = out.File
	file_artifact_proto_goTypes = nil
	file_artifact_proto_depIdxs = nil
}
