// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: event.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorType int32

const (
	ActorType_ACTOR_TYPE_UNSPECIFIED ActorType = 0
	ActorType_ACTOR_TYPE_HUMAN       ActorType = 1
	ActorType_ACTOR_TYPE_AGENT       ActorType = 2
	ActorType_ACTOR_TYPE_SYSTEM      ActorType = 3
)

// Enum value maps for ActorType.
var (
	ActorType_name = map[int32]string{
		0: "ACTOR_TYPE_UNSPECIFIED",
		1: "ACTOR_TYPE_HUMAN",
		2: "ACTOR_TYPE_AGENT",
		3: "ACTOR_TYPE_SYSTEM",
	}
	ActorType_value = map[string]int32{
		"ACTOR_TYPE_UNSPECIFIED": 0,
		"ACTOR_TYPE_HUMAN":       1,
		"ACTOR_TYPE_AGENT":       2,
		"ACTOR_TYPE_SYSTEM":      3,
	}
)

func (x ActorType) Enum() *ActorType {
	p := new(ActorType)
	*p = x
	return p
}

func (x ActorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (ActorType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x ActorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorType.Descriptor instead.
func (ActorType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED EventKind = 0
	EventKind_EVENT_KIND_PROMPT      EventKind = 1
	EventKind_EVENT_KIND_THOUGHT     EventKind = 2
	EventKind_EVENT_KIND_TOOL_CALL   EventKind = 3
	EventKind_EVENT_KIND_TOOL_RESULT EventKind = 4
	EventKind_EVENT_KIND_CODE_CHANGE EventKind = 5
	EventKind_EVENT_KIND_COMMIT      EventKind = 6
	EventKind_EVENT_KIND_PR          EventKind = 7
	EventKind_EVENT_KIND_TEST_RUN    EventKind = 8
	EventKind_EVENT_KIND_BUILD       EventKind = 9
	EventKind_EVENT_KIND_DEPLOY      EventKind = 10
	EventKind_EVENT_KIND_REVIEW      EventKind = 11
	EventKind_EVENT_KIND_DECISION    EventKind = 12
	EventKind_EVENT_KIND_PUSH        EventKind = 13
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0:  "EVENT_KIND_UNSPECIFIED",
		1:  "EVENT_KIND_PROMPT",
		2:  "EVENT_KIND_THOUGHT",
		3:  "EVENT_KIND_TOOL_CALL",
		4:  "EVENT_KIND_TOOL_RESULT",
		5:  "EVENT_KIND_CODE_CHANGE",
		6:  "EVENT_KIND_COMMIT",
		7:  "EVENT_KIND_PR",
		8:  "EVENT_KIND_TEST_RUN",
		9:  "EVENT_KIND_BUILD",
		10: "EVENT_KIND_DEPLOY",
		11: "EVENT_KIND_REVIEW",
		12: "EVENT_KIND_DECISION",
		13: "EVENT_KIND_PUSH",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED": 0,
		"EVENT_KIND_PROMPT":      1,
		"EVENT_KIND_THOUGHT":     2,
		"EVENT_KIND_TOOL_CALL":   3,
		"EVENT_KIND_TOOL_RESULT": 4,
		"EVENT_KIND_CODE_CHANGE": 5,
		"EVENT_KIND_COMMIT":      6,
		"EVENT_KIND_PR":          7,
		"EVENT_KIND_TEST_RUN":    8,
		"EVENT_KIND_BUILD":       9,
		"EVENT_KIND_DEPLOY":      10,
		"EVENT_KIND_REVIEW":      11,
		"EVENT_KIND_DECISION":    12,
		"EVENT_KIND_PUSH":        13,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[1].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[1]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

// Event is the canonical record for one observable action in the human-agent
// coding pipeline. Events are append-only and form a hash chain via prev_hash.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ULID
	Ts            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TurnId        string                 `protobuf:"bytes,4,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	Actor         *Actor                 `protobuf:"bytes,5,opt,name=actor,proto3" json:"actor,omitempty"`
	Kind          EventKind              `protobuf:"varint,6,opt,name=kind,proto3,enum=agentlens.v1.EventKind" json:"kind,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`                    // kind-specific
	Parents       []string               `protobuf:"bytes,8,rep,name=parents,proto3" json:"parents,omitempty"`                    // causal upstream event IDs
	Refs          []string               `protobuf:"bytes,9,rep,name=refs,proto3" json:"refs,omitempty"`                          // referenced artifact IDs
	Hash          string                 `protobuf:"bytes,10,opt,name=hash,proto3" json:"hash,omitempty"`                         // hash(serialized event - hash - sig)
	PrevHash      string                 `protobuf:"bytes,11,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"` // hash of previous event in chain
	Sig           []byte                 `protobuf:"bytes,12,opt,name=sig,proto3" json:"sig,omitempty"`                           // optional ed25519 signature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *Event) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *Event) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *Event) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetParents() []string {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *Event) GetRefs() []string {
	if x != nil {
		return x.Refs
	}
	return nil
}

func (x *Event) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Event) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *Event) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ActorType              `protobuf:"varint,1,opt,name=type,proto3,enum=agentlens.v1.ActorType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"` // populated when type=AGENT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *Actor) GetType() ActorType {
	if x != nil {
		return x.Type
	}
	return ActorType_ACTOR_TYPE_UNSPECIFIED
}

func (x *Actor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Actor) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\fagentlens.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x02ts\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x17\n" +
	"\aturn_id\x18\x04 \x01(\tR\x06turnId\x12)\n" +
	"\x05actor\x18\x05 \x01(\v2\x13.agentlens.v1.ActorR\x05actor\x12+\n" +
	"\x04kind\x18\x06 \x01(\x0e2\x17.agentlens.v1.EventKindR\x04kind\x121\n" +
	"\apayload\x18\a \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x18\n" +
	"\aparents\x18\b \x03(\tR\aparents\x12\x12\n" +
	"\x04refs\x18\t \x03(\tR\x04refs\x12\x12\n" +
	"\x04hash\x18\n" +
	" \x01(\tR\x04hash\x12\x1b\n" +
	"\tprev_hash\x18\v \x01(\tR\bprevHash\x12\x10\n" +
	"\x03sig\x18\f \x01(\fR\x03sig\"Z\n" +
	"\x05Actor\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.agentlens.v1.ActorTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model*j\n" +
	"\tActorType\x12\x1a\n" +
	"\x16ACTOR_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACTOR_TYPE_HUMAN\x10\x01\x12\x14\n" +
	"\x10ACTOR_TYPE_AGENT\x10\x02\x12\x15\n" +
	"\x11ACTOR_TYPE_SYSTEM\x10\x03*\xdd\x02\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EVENT_KIND_PROMPT\x10\x01\x12\x16\n" +
	"\x12EVENT_KIND_THOUGHT\x10\x02\x12\x18\n" +
	"\x14EVENT_KIND_TOOL_CALL\x10\x03\x12\x1a\n" +
	"\x16EVENT_KIND_TOOL_RESULT\x10\x04\x12\x1a\n" +
	"\x16EVENT_KIND_CODE_CHANGE\x10\x05\x12\x15\n" +
	"\x11EVENT_KIND_COMMIT\x10\x06\x12\x11\n" +
	"\rEVENT_KIND_PR\x10\a\x12\x17\n" +
	"\x13EVENT_KIND_TEST_RUN\x10\b\x12\x14\n" +
	"\x10EVENT_KIND_BUILD\x10\t\x12\x15\n" +
	"\x11EVENT_KIND_DEPLOY\x10\n" +
	"\x12\x15\n" +
	"\x11EVENT_KIND_REVIEW\x10\v\x12\x17\n" +
	"\x13EVENT_KIND_DECISION\x10\f\x12\x13\n" +
	"\x0fEVENT_KIND_PUSH\x10\rB/Z-github.com/dong-qiu/agent-lens/internal/pb;pbb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_event_proto_goTypes = []any{
	(ActorType)(0),                // 0: agentlens.v1.ActorType
	(EventKind)(0),                // 1: agentlens.v1.EventKind
	(*Event)(nil),                 // 2: agentlens.v1.Event
	(*Actor)(nil),                 // 3: agentlens.v1.Actor
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
}
var file_event_proto_depIdxs = []int32{
	4, // 0: agentlens.v1.Event.ts:type_name -> google.protobuf.Timestamp
	3, // 1: agentlens.v1.Event.actor:type_name -> agentlens.v1.Actor
	1, // 2: agentlens.v1.Event.kind:type_name -> agentlens.v1.EventKind
	5, // 3: agentlens.v1.Event.payload:type_name -> google.protobuf.Struct
	0, // 4: agentlens.v1.Actor.type:type_name -> agentlens.v1.ActorType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
