// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: link.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Relation int32

const (
	Relation_RELATION_UNSPECIFIED Relation = 0
	Relation_RELATION_PRODUCES    Relation = 1
	Relation_RELATION_REFERENCES  Relation = 2
	Relation_RELATION_REVIEWS     Relation = 3
	Relation_RELATION_BUILDS      Relation = 4
	Relation_RELATION_DEPLOYS     Relation = 5
)

// Enum value maps for Relation.
var (
	Relation_name = map[int32]string{
		0: "RELATION_UNSPECIFIED",
		1: "RELATION_PRODUCES",
		2: "RELATION_REFERENCES",
		3: "RELATION_REVIEWS",
		4: "RELATION_BUILDS",
		5: "RELATION_DEPLOYS",
	}
	Relation_value = map[string]int32{
		"RELATION_UNSPECIFIED": 0,
		"RELATION_PRODUCES":    1,
		"RELATION_REFERENCES":  2,
		"RELATION_REVIEWS":     3,
		"RELATION_BUILDS":      4,
		"RELATION_DEPLOYS":     5,
	}
)

func (x Relation) Enum() *Relation {
	p := new(Relation)
	*p = x
	return p
}

func (x Relation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Relation) Descriptor() protoreflect.EnumDescriptor {
	return file_link_proto_enumTypes[0].Descriptor()
}

func (Relation) Type() protoreflect.EnumType {
	return &file_link_proto_enumTypes[0]
}

func (x Relation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Relation.Descriptor instead.
func (Relation) EnumDescriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{0}
}

// Link expresses a causal or semantic relation between two events.
// Stored separately from events so linking can be re-derived without
// rewriting the append-only event log.
type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromEvent     string                 `protobuf:"bytes,1,opt,name=from_event,json=fromEvent,proto3" json:"from_event,omitempty"`
	ToEvent       string                 `protobuf:"bytes,2,opt,name=to_event,json=toEvent,proto3" json:"to_event,omitempty"`
	Relation      Relation               `protobuf:"varint,3,opt,name=relation,proto3,enum=agentlens.v1.Relation" json:"relation,omitempty"`
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`                 // 0.0 .. 1.0
	InferredBy    string                 `protobuf:"bytes,5,opt,name=inferred_by,json=inferredBy,proto3" json:"inferred_by,omitempty"` // rule id, or "manual"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetFromEvent() string {
	if x != nil {
		return x.FromEvent
	}
	return ""
}

func (x *Link) GetToEvent() string {
	if x != nil {
		return x.ToEvent
	}
	return ""
}

func (x *Link) GetRelation() Relation {
	if x != nil {
		return x.Relation
	}
	return Relation_RELATION_UNSPECIFIED
}

func (x *Link) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Link) GetInferredBy() string {
	if x != nil {
		return x.InferredBy
	}
	return ""
}

var File_link_proto protoreflect.FileDescriptor

const file_link_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"link.proto\x12\fagentlens.v1\"\xb5\x01\n" +
	"\x04Link\x12\x1d\n" +
	"\n" +
	"from_event\x18\x01 \x01(\tR\tfromEvent\x12\x19\n" +
	"\bto_event\x18\x02 \x01(\tR\atoEvent\x122\n" +
	"\brelation\x18\x03 \x01(\x0e2\x16.agentlens.v1.RelationR\brelation\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12\x1f\n" +
	"\vinferred_by\x18\x05 \x01(\tR\n" +
	"inferredBy*\x95\x01\n" +
	"\bRelation\x12\x18\n" +
	"\x14RELATION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RELATION_PRODUCES\x10\x01\x12\x17\n" +
	"\x13RELATION_REFERENCES\x10\x02\x12\x14\n" +
	"\x10RELATION_REVIEWS\x10\x03\x12\x13\n" +
	"\x0fRELATION_BUILDS\x10\x04\x12\x14\n" +
	"\x10RELATION_DEPLOYS\x10\x05B/Z-github.com/dong-qiu/agent-lens/internal/pb;pbb\x06proto3"

var (
	file_link_proto_rawDescOnce sync.Once
	file_link_proto_rawDescData []byte
)

func file_link_proto_rawDescGZIP() []byte {
	file_link_proto_rawDescOnce.Do(func() {
		file_link_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_link_proto_rawDesc), len(file_link_proto_rawDesc)))
	})
	return file_link_proto_rawDescData
}

var file_link_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_link_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_link_proto_goTypes = []any{
	(Relation)(0), // 0: agentlens.v1.Relation
	(*Link)(nil),  // 1: agentlens.v1.Link
}
var file_link_proto_depIdxs = []int32{
	0, // 0: agentlens.v1.Link.relation:type_name -> agentlens.v1.Relation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_link_proto_init() }
func file_link_proto_init() {
	if File_link_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_link_proto_rawDesc), len(file_link_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_link_proto_goTypes,
		DependencyIndexes: file_link_proto_depIdxs,
		EnumInfos:         file_link_proto_enumTypes,
		MessageInfos:      file_link_proto_msgTypes,
	}.Build()
	File_link_proto = out.File
	file_link_proto_goTypes = nil
	file_link_proto_depIdxs = nil
}
