// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package query

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Actor struct {
	Type  ActorType `json:"type"`
	ID    string    `json:"id"`
	Model *string   `json:"model,omitempty"`
}

type Event struct {
	ID        string         `json:"id"`
	Ts        time.Time      `json:"ts"`
	SessionID string         `json:"sessionId"`
	TurnID    *string        `json:"turnId,omitempty"`
	Actor     *Actor         `json:"actor"`
	Kind      EventKind      `json:"kind"`
	Payload   map[string]any `json:"payload,omitempty"`
	Parents   []string       `json:"parents"`
	Refs      []string       `json:"refs"`
	Hash      string         `json:"hash"`
	PrevHash  *string        `json:"prevHash,omitempty"`
	// All links touching this event in either direction (from/to).
	Links []*Link `json:"links"`
	// Token usage of the assistant message that derived this event. Present
	// only on events derived from a real-usage assistant message (per ADR
	// 0002 D3, `<synthetic>` placeholders and all-zero messages return
	// null). The carrier event per message is the first text block, then
	// the first thinking block, then a synthesized stub — so usage never
	// double-counts in turn / session aggregation.
	Usage *TokenUsage `json:"usage,omitempty"`
	// Reason the model stopped on the message that derived this event:
	// `end_turn`, `tool_use`, `stop_sequence`, etc. Sourced verbatim from
	// the Anthropic transcript `message.stop_reason` field.
	StopReason *string `json:"stopReason,omitempty"`
}

type Link struct {
	FromEvent  string  `json:"fromEvent"`
	ToEvent    string  `json:"toEvent"`
	Relation   string  `json:"relation"`
	Confidence float64 `json:"confidence"`
	InferredBy string  `json:"inferredBy"`
}

type Query struct {
}

// Aggregated view of a session: id plus first/last activity and event count.
type Session struct {
	ID           string    `json:"id"`
	FirstEventAt time.Time `json:"firstEventAt"`
	LastEventAt  time.Time `json:"lastEventAt"`
	EventCount   int       `json:"eventCount"`
	// Aggregate token usage across every event in this session that has
	// `usage`. Numeric counters (input/output/cache_read/cache_write) are
	// exact sums. Non-numeric fields summarize: `vendor` is the dominant
	// value (or empty if mixed); `model` is empty when more than one model
	// appeared (multi-model sessions), else the single model id;
	// `serviceTier` likewise. Returns null when no event in the session
	// carries usage.
	TotalUsage *TokenUsage `json:"totalUsage,omitempty"`
}

// Vendor-neutral token-counting shape per ADR 0002 D2. Per-event usage
// exposes vendor / model / service_tier of the originating message.
//
// When returned as `Session.totalUsage`, only numeric counters aggregate
// meaningfully; vendor / model / service_tier carry best-effort summary
// values (see Session.totalUsage docs). Cache and server-tool fields are
// optional because some vendors (e.g. OpenAI) don't have a directly
// comparable concept.
type TokenUsage struct {
	Vendor             string  `json:"vendor"`
	Model              string  `json:"model"`
	ServiceTier        *string `json:"serviceTier,omitempty"`
	InputTokens        int     `json:"inputTokens"`
	OutputTokens       int     `json:"outputTokens"`
	CacheReadTokens    *int    `json:"cacheReadTokens,omitempty"`
	CacheWrite5mTokens *int    `json:"cacheWrite5mTokens,omitempty"`
	CacheWrite1hTokens *int    `json:"cacheWrite1hTokens,omitempty"`
	WebSearchCalls     *int    `json:"webSearchCalls,omitempty"`
	WebFetchCalls      *int    `json:"webFetchCalls,omitempty"`
}

type ActorType string

const (
	ActorTypeHuman  ActorType = "HUMAN"
	ActorTypeAgent  ActorType = "AGENT"
	ActorTypeSystem ActorType = "SYSTEM"
)

var AllActorType = []ActorType{
	ActorTypeHuman,
	ActorTypeAgent,
	ActorTypeSystem,
}

func (e ActorType) IsValid() bool {
	switch e {
	case ActorTypeHuman, ActorTypeAgent, ActorTypeSystem:
		return true
	}
	return false
}

func (e ActorType) String() string {
	return string(e)
}

func (e *ActorType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActorType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActorType", str)
	}
	return nil
}

func (e ActorType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActorType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActorType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EventKind string

const (
	EventKindPrompt     EventKind = "PROMPT"
	EventKindThought    EventKind = "THOUGHT"
	EventKindToolCall   EventKind = "TOOL_CALL"
	EventKindToolResult EventKind = "TOOL_RESULT"
	EventKindCodeChange EventKind = "CODE_CHANGE"
	EventKindCommit     EventKind = "COMMIT"
	EventKindPr         EventKind = "PR"
	EventKindTestRun    EventKind = "TEST_RUN"
	EventKindBuild      EventKind = "BUILD"
	EventKindDeploy     EventKind = "DEPLOY"
	EventKindReview     EventKind = "REVIEW"
	EventKindDecision   EventKind = "DECISION"
	EventKindPush       EventKind = "PUSH"
)

var AllEventKind = []EventKind{
	EventKindPrompt,
	EventKindThought,
	EventKindToolCall,
	EventKindToolResult,
	EventKindCodeChange,
	EventKindCommit,
	EventKindPr,
	EventKindTestRun,
	EventKindBuild,
	EventKindDeploy,
	EventKindReview,
	EventKindDecision,
	EventKindPush,
}

func (e EventKind) IsValid() bool {
	switch e {
	case EventKindPrompt, EventKindThought, EventKindToolCall, EventKindToolResult, EventKindCodeChange, EventKindCommit, EventKindPr, EventKindTestRun, EventKindBuild, EventKindDeploy, EventKindReview, EventKindDecision, EventKindPush:
		return true
	}
	return false
}

func (e EventKind) String() string {
	return string(e)
}

func (e *EventKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventKind", str)
	}
	return nil
}

func (e EventKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EventKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EventKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
