// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package query

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Actor struct {
	Type  ActorType `json:"type"`
	ID    string    `json:"id"`
	Model *string   `json:"model,omitempty"`
}

type Event struct {
	ID        string         `json:"id"`
	Ts        time.Time      `json:"ts"`
	SessionID string         `json:"sessionId"`
	TurnID    *string        `json:"turnId,omitempty"`
	Actor     *Actor         `json:"actor"`
	Kind      EventKind      `json:"kind"`
	Payload   map[string]any `json:"payload,omitempty"`
	Parents   []string       `json:"parents"`
	Refs      []string       `json:"refs"`
	Hash      string         `json:"hash"`
	PrevHash  *string        `json:"prevHash,omitempty"`
	// All links touching this event in either direction (from/to).
	Links []*Link `json:"links"`
}

type Link struct {
	FromEvent  string  `json:"fromEvent"`
	ToEvent    string  `json:"toEvent"`
	Relation   string  `json:"relation"`
	Confidence float64 `json:"confidence"`
	InferredBy string  `json:"inferredBy"`
}

type Query struct {
}

type ActorType string

const (
	ActorTypeHuman  ActorType = "HUMAN"
	ActorTypeAgent  ActorType = "AGENT"
	ActorTypeSystem ActorType = "SYSTEM"
)

var AllActorType = []ActorType{
	ActorTypeHuman,
	ActorTypeAgent,
	ActorTypeSystem,
}

func (e ActorType) IsValid() bool {
	switch e {
	case ActorTypeHuman, ActorTypeAgent, ActorTypeSystem:
		return true
	}
	return false
}

func (e ActorType) String() string {
	return string(e)
}

func (e *ActorType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActorType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActorType", str)
	}
	return nil
}

func (e ActorType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActorType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActorType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EventKind string

const (
	EventKindPrompt     EventKind = "PROMPT"
	EventKindThought    EventKind = "THOUGHT"
	EventKindToolCall   EventKind = "TOOL_CALL"
	EventKindToolResult EventKind = "TOOL_RESULT"
	EventKindCodeChange EventKind = "CODE_CHANGE"
	EventKindCommit     EventKind = "COMMIT"
	EventKindPr         EventKind = "PR"
	EventKindTestRun    EventKind = "TEST_RUN"
	EventKindBuild      EventKind = "BUILD"
	EventKindDeploy     EventKind = "DEPLOY"
	EventKindReview     EventKind = "REVIEW"
	EventKindDecision   EventKind = "DECISION"
	EventKindPush       EventKind = "PUSH"
)

var AllEventKind = []EventKind{
	EventKindPrompt,
	EventKindThought,
	EventKindToolCall,
	EventKindToolResult,
	EventKindCodeChange,
	EventKindCommit,
	EventKindPr,
	EventKindTestRun,
	EventKindBuild,
	EventKindDeploy,
	EventKindReview,
	EventKindDecision,
	EventKindPush,
}

func (e EventKind) IsValid() bool {
	switch e {
	case EventKindPrompt, EventKindThought, EventKindToolCall, EventKindToolResult, EventKindCodeChange, EventKindCommit, EventKindPr, EventKindTestRun, EventKindBuild, EventKindDeploy, EventKindReview, EventKindDecision, EventKindPush:
		return true
	}
	return false
}

func (e EventKind) String() string {
	return string(e)
}

func (e *EventKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EventKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EventKind", str)
	}
	return nil
}

func (e EventKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EventKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EventKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
