package query

import "github.com/dong-qiu/agent-lens/internal/store"

// Resolver is the root of the GraphQL resolver tree. Dependencies are
// injected at construction time and accessed by the per-type resolver
// implementations in *.resolvers.go (generated by gqlgen). gqlgen will
// detect this file and skip generating its own resolver.go.
type Resolver struct {
	Store store.Store
}

func NewResolver(s store.Store) *Resolver {
	return &Resolver{Store: s}
}
