package query

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"time"

	"github.com/dongqiu/agent-lens/internal/store"
)

// Links is the resolver for the links field.
func (r *eventResolver) Links(ctx context.Context, obj *Event) ([]*Link, error) {
	if obj == nil {
		return nil, nil
	}
	raw, err := r.Store.LinksForEvent(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	out := make([]*Link, 0, len(raw))
	for _, l := range raw {
		out = append(out, toGQLLink(l))
	}
	return out, nil
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (*Event, error) {
	se, err := r.Store.GetEvent(ctx, id)
	if errors.Is(err, store.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return toGQLEvent(se), nil
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, sessionID string, limit *int) ([]*Event, error) {
	n := 100
	if limit != nil {
		n = *limit
	}
	list, err := r.Store.ListBySession(ctx, sessionID, n)
	if err != nil {
		return nil, err
	}
	out := make([]*Event, 0, len(list))
	for _, se := range list {
		out = append(out, toGQLEvent(se))
	}
	return out, nil
}

// SessionHead is the resolver for the sessionHead field.
func (r *queryResolver) SessionHead(ctx context.Context, sessionID string) (string, error) {
	return r.Store.HeadHash(ctx, sessionID)
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, limit *int, since *time.Time) ([]*Session, error) {
	n := 50
	if limit != nil {
		n = *limit
	}
	var sinceVal time.Time
	if since != nil {
		sinceVal = *since
	}
	list, err := r.Store.ListSessions(ctx, n, sinceVal)
	if err != nil {
		return nil, err
	}
	out := make([]*Session, 0, len(list))
	for _, s := range list {
		out = append(out, toGQLSession(s))
	}
	return out, nil
}

// Event returns EventResolver implementation.
func (r *Resolver) Event() EventResolver { return &eventResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type eventResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
