package query

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/dongqiu/agent-lens/internal/store"
)

// Links is the resolver for the links field.
func (r *eventResolver) Links(ctx context.Context, obj *Event) ([]*Link, error) {
	if obj == nil {
		return nil, nil
	}
	raw, err := r.Store.LinksForEvent(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	out := make([]*Link, 0, len(raw))
	for _, l := range raw {
		out = append(out, toGQLLink(l))
	}
	return out, nil
}

// Usage is the resolver for the usage field.
func (r *eventResolver) Usage(ctx context.Context, obj *Event) (*TokenUsage, error) {
	if obj == nil {
		return nil, nil
	}
	return decodePayloadUsage(obj.Payload), nil
}

// StopReason is the resolver for the stopReason field.
func (r *eventResolver) StopReason(ctx context.Context, obj *Event) (*string, error) {
	if obj == nil {
		return nil, nil
	}
	return decodePayloadStopReason(obj.Payload), nil
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (*Event, error) {
	se, err := r.Store.GetEvent(ctx, id)
	if errors.Is(err, store.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return toGQLEvent(se), nil
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, sessionID string, limit *int) ([]*Event, error) {
	n := 100
	if limit != nil {
		n = *limit
	}
	list, err := r.Store.ListBySession(ctx, sessionID, n)
	if err != nil {
		return nil, err
	}
	out := make([]*Event, 0, len(list))
	for _, se := range list {
		out = append(out, toGQLEvent(se))
	}
	return out, nil
}

// SessionHead is the resolver for the sessionHead field.
func (r *queryResolver) SessionHead(ctx context.Context, sessionID string) (string, error) {
	return r.Store.HeadHash(ctx, sessionID)
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, limit *int, since *time.Time) ([]*Session, error) {
	n := 50
	if limit != nil {
		n = *limit
	}
	var sinceVal time.Time
	if since != nil {
		sinceVal = *since
	}
	list, err := r.Store.ListSessions(ctx, n, sinceVal)
	if err != nil {
		return nil, err
	}
	out := make([]*Session, 0, len(list))
	for _, s := range list {
		out = append(out, toGQLSession(s))
	}
	return out, nil
}

// LinkedEvents is the resolver for the linkedEvents field.
//
// BFS by session: start from sessionID, list its events, then expand
// to any session reachable via links, repeating up to `depth` hops.
//
// Critical: link discovery uses Store.LinksForSession (full table
// scan filtered by session) rather than walking links per fetched
// event. The latter would cap discovery at perSessionLimit events,
// silently missing links that live on events past that cap — exactly
// what the dogfood data hit (the link-bearing tool_result was past
// row 900 of a 1000-event session).
func (r *queryResolver) LinkedEvents(ctx context.Context, sessionID string, depth *int, perSessionLimit *int) ([]*Event, error) {
	d := 1
	if depth != nil {
		d = *depth
	}
	if d < 0 {
		d = 0
	}
	if d > 3 {
		d = 3
	}

	psl := 200
	if perSessionLimit != nil {
		psl = *perSessionLimit
	}

	visited := map[string]bool{sessionID: true}
	frontier := []string{sessionID}
	var collected []*store.Event

	collectedIDs := map[string]bool{}
	for level := 0; level <= d && len(frontier) > 0; level++ {
		var nextFrontier []string
		for _, sid := range frontier {
			evs, err := r.Store.ListBySession(ctx, sid, psl)
			if err != nil {
				return nil, fmt.Errorf("ListBySession(%q): %w", sid, err)
			}
			for _, e := range evs {
				if !collectedIDs[e.ID] {
					collectedIDs[e.ID] = true
					collected = append(collected, e)
				}
			}

			// Always pull the links touching this session so we (a) can
			// expand the frontier and (b) can guarantee link-bearing
			// events from this session are present in the result even
			// when they sit past `psl`. Without that guarantee, a
			// cross-session edge whose anchor-side endpoint was paged
			// out would render as an orphan and ReactFlow would
			// silently drop it — the user sees neighbouring events
			// floating with no visible connection back.
			links, err := r.Store.LinksForSession(ctx, sid)
			if err != nil {
				// Tolerate per-session link lookup failures — they'd
				// only suppress neighbour discovery, not corrupt the
				// already-collected events.
				continue
			}
			for _, l := range links {
				for _, otherID := range [2]string{l.FromEvent, l.ToEvent} {
					other, err := r.Store.GetEvent(ctx, otherID)
					if err != nil || other == nil {
						continue
					}
					// Patch in this-session link endpoints that fell
					// past psl, so cross-session edges always have
					// both endpoints in the rendered set. Also fetch
					// a small chain-context window before the bearer
					// so the dashed prev_hash edge has a rendered
					// source — without this the bearer floats with no
					// chain connection back to the originating
					// TOOL_CALL even though we successfully patched
					// it in.
					if other.SessionID == sid && !collectedIDs[other.ID] {
						collectedIDs[other.ID] = true
						collected = append(collected, other)
						const chainContext = 10
						preds, perr := r.Store.EventsBeforeID(ctx, sid, other.ID, chainContext)
						if perr == nil {
							for _, p := range preds {
								if !collectedIDs[p.ID] {
									collectedIDs[p.ID] = true
									collected = append(collected, p)
								}
							}
						}
					}
					if level < d && !visited[other.SessionID] {
						visited[other.SessionID] = true
						nextFrontier = append(nextFrontier, other.SessionID)
					}
				}
			}
		}
		frontier = nextFrontier
	}

	out := make([]*Event, 0, len(collected))
	for _, se := range collected {
		out = append(out, toGQLEvent(se))
	}
	return out, nil
}

// TotalUsage is the resolver for the totalUsage field.
//
// Loads every event in the session (limit=0 → unlimited) and walks
// payload.usage on each. Aggregation is in-Go rather than SQL so the
// memory store works the same way as Postgres; pushing this to a SQL
// `SUM()` is a future optimization once sessions push past tens of
// thousands of events.
func (r *sessionResolver) TotalUsage(ctx context.Context, obj *Session) (*TokenUsage, error) {
	if obj == nil {
		return nil, nil
	}
	events, err := r.Store.ListBySession(ctx, obj.ID, 0)
	if err != nil {
		return nil, err
	}
	return aggregateSessionUsage(events), nil
}

// Event returns EventResolver implementation.
func (r *Resolver) Event() EventResolver { return &eventResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Session returns SessionResolver implementation.
func (r *Resolver) Session() SessionResolver { return &sessionResolver{r} }

type eventResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type sessionResolver struct{ *Resolver }
