package query

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/dongqiu/agent-lens/internal/store"
)

// Links is the resolver for the links field.
func (r *eventResolver) Links(ctx context.Context, obj *Event) ([]*Link, error) {
	if obj == nil {
		return nil, nil
	}
	raw, err := r.Store.LinksForEvent(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	out := make([]*Link, 0, len(raw))
	for _, l := range raw {
		out = append(out, toGQLLink(l))
	}
	return out, nil
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (*Event, error) {
	se, err := r.Store.GetEvent(ctx, id)
	if errors.Is(err, store.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return toGQLEvent(se), nil
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, sessionID string, limit *int) ([]*Event, error) {
	n := 100
	if limit != nil {
		n = *limit
	}
	list, err := r.Store.ListBySession(ctx, sessionID, n)
	if err != nil {
		return nil, err
	}
	out := make([]*Event, 0, len(list))
	for _, se := range list {
		out = append(out, toGQLEvent(se))
	}
	return out, nil
}

// SessionHead is the resolver for the sessionHead field.
func (r *queryResolver) SessionHead(ctx context.Context, sessionID string) (string, error) {
	return r.Store.HeadHash(ctx, sessionID)
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, limit *int, since *time.Time) ([]*Session, error) {
	n := 50
	if limit != nil {
		n = *limit
	}
	var sinceVal time.Time
	if since != nil {
		sinceVal = *since
	}
	list, err := r.Store.ListSessions(ctx, n, sinceVal)
	if err != nil {
		return nil, err
	}
	out := make([]*Session, 0, len(list))
	for _, s := range list {
		out = append(out, toGQLSession(s))
	}
	return out, nil
}

// LinkedEvents is the resolver for the linkedEvents field.
//
// BFS by session: start from sessionID, list its events, then expand
// to any session reachable via links, repeating up to `depth` hops.
//
// Critical: link discovery uses Store.LinksForSession (full table
// scan filtered by session) rather than walking links per fetched
// event. The latter would cap discovery at perSessionLimit events,
// silently missing links that live on events past that cap — exactly
// what the dogfood data hit (the link-bearing tool_result was past
// row 900 of a 1000-event session).
func (r *queryResolver) LinkedEvents(ctx context.Context, sessionID string, depth *int, perSessionLimit *int) ([]*Event, error) {
	d := 1
	if depth != nil {
		d = *depth
	}
	if d < 0 {
		d = 0
	}
	if d > 3 {
		d = 3
	}

	psl := 200
	if perSessionLimit != nil {
		psl = *perSessionLimit
	}

	visited := map[string]bool{sessionID: true}
	frontier := []string{sessionID}
	var collected []*store.Event

	for level := 0; level <= d && len(frontier) > 0; level++ {
		var nextFrontier []string
		for _, sid := range frontier {
			evs, err := r.Store.ListBySession(ctx, sid, psl)
			if err != nil {
				return nil, fmt.Errorf("ListBySession(%q): %w", sid, err)
			}
			collected = append(collected, evs...)

			if level == d {
				continue // last layer — don't expand further
			}
			links, err := r.Store.LinksForSession(ctx, sid)
			if err != nil {
				// Tolerate per-session link lookup failures — they'd
				// only suppress neighbour discovery, not corrupt the
				// already-collected events.
				continue
			}
			for _, l := range links {
				for _, otherID := range [2]string{l.FromEvent, l.ToEvent} {
					other, err := r.Store.GetEvent(ctx, otherID)
					if err != nil || other == nil {
						continue
					}
					if !visited[other.SessionID] {
						visited[other.SessionID] = true
						nextFrontier = append(nextFrontier, other.SessionID)
					}
				}
			}
		}
		frontier = nextFrontier
	}

	out := make([]*Event, 0, len(collected))
	for _, se := range collected {
		out = append(out, toGQLEvent(se))
	}
	return out, nil
}

// Event returns EventResolver implementation.
func (r *Resolver) Event() EventResolver { return &eventResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type eventResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
